apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: fleetautoscalerwebhook-aetherroyale-game-server
  namespace: gameservers
spec:
  # Nom de la flotte à laquelle se connecter. Doit correspondre à une flotte existante dans le même espace de noms (namespace) que ce FleetAutoscaler.
  fleetName: fleet-aetherroyale-game-server # Dois avoir le meme nom exact que la ressource "Fleet" deployer.
  policy:
    type: Webhook
    webhook:
      # Endpoint HTTPS public de ton webhook
      # ⚠️ Pas besoin de caBundle si le certificat est signé par une CA reconnue (ex: Let's Encrypt)
      url: https://staging.api.aetherroyale.crzgames.com/agones/fleet/autoscale # Request HTTP/HTTPS de type POST
  sync:
    # Type de synchronisation. Pour l'instant, seul FixedInterval est disponible.
    type: FixedInterval
    # paramètres de la synchronisation à intervalle fixe
    fixedInterval:
      # le temps en secondes entre chaque mise à l'échelle automatique
      seconds: 30