# Exemple pour l'API Kubernetes GameServerAllocation d'Agones, mais on utilisera 
# plutôt le service Agones Allocator via gRPC dans notre cas, ce qui est plus rapide que l'API Kubernetes.
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
metadata:
  name: test-allocation
  namespace: gameservers   # ← IMPORTANT : doit être le même que celui de la flotte ciblée
spec:
  selectors:
    - matchLabels:
        # Nom exact de la flotte (Fleet) ciblée pour l'allocation d'un GameServer dans la flotte "fleet-aetherroyale-game-server" créée précédemment.
        agones.dev/fleet: fleet-aetherroyale-game-server
  metadata:
    annotations:
      # L'ensemble des jetons d'accès pour le point de terminaison associé peut être défini 
      # en ajoutant des chaînes de caractères standard encodées en base64, séparées par des virgules.
      quilkin.dev/tokens: MDAwMDAwMDAwMDAwMDQ1Ng== # Base64 de 0000000000000456 = MDAwMDAwMDAwMDAwMDQ1Ng== (16 bytes)

